# errata:
# - sudo/dist/group are set so as to get Blue Box VMs, necessary for [loopback]
#   IPv6 support
 
sudo: required
dist: focal

os: linux
language: c++

addons:
  sonarcloud:
    organization: "kiiglobal"
    token:
      secure: "Lt5NPtLvE0jdWsISPZRJ995R3nvjbxZU+oITGOXrvGvgzX+8x3X0lmibpUH1lT9MOlF4atNsqFXeOnKTiXWa2zpX+hNEwdfgfMRR2kCU5V6aMtfsUz3SPm+Auxud+0SAV3THi6zNbR3tviGWVAIhg0zx25G1QakbnFQD41gzSRpqNPyeLZCAzx91bwUKyC0b8AiSk1x9/Izhnv8bqFDZXPZqHEjKv5VX/Sk5htAeojxb6Looa/RU0nc25wK5ndOvun53iTUqwyJaEDk40jR93X84MquRULUNyeKCVs47wSz1enza5gjemhZDFE1G65BNsYm5peO3LMgf2GQb/13WIErdR5yOxGp85AFKv0kn/2NabeRMe1Hgim8WwCh6cV7OkDiHicuMBcYsI4JB2owqlC9dO3HphUxHacwBiqjTLozPsv5V0SZiAixF6UpQheW8dSBtqu63Mfq47znUsQrSH9T4wSzDtFS8bWTE4WwZqYjMVVDo0bwKrM5k9hqLE0jg7vKyG2tVjpIcvItuMm+gEiD9QnCR7r2eMTE6JXnFuR/eYKjAALMkgWHdRGyQpmkXUJmIJeRJgzHp7mFtnjScnkCERlJVQ5AlE3kkSQjVmblTZ2i8mXTSa9HVyjjgye+EDQyOjSzfD59wy6aqlW6WNmEdN7Mrx729xgNRYihWVBs="

services:
  - docker

cache:
  ccache: true
  directories:
    - $HOME/cache

env:
  global:
    - SONAR_TOKEN: "2145a165fed83cfe944b62f6f8bd552860cb5931"
    # DOCKER_HUB_USER
    - secure: "HzDlVXb4C7H3FOnuOu1TiyYzx1EXTcY3KS5oItO+h23UHZLl6K7xqp38sRimIT4CrfB6fD8Xia7hQvY6MLts/r7yBUV90YSgxsmGg1iTiDa9jRW6orVAB2z5drkDHGWyF0PaJy9skY0f2dWljL1Lk9g0Ef+pyJz/P/H03Pv3Nx5JdJs+IfU6DXlRq1dsqgRWNsrVJSMvRuZeP0V5kjaoeafdyma6Ehj8yVsRbznSH1qFuWs4TPC/8J2L1QngtLd9MvnlnUGRjrUUoQS1GpR/UJ9/TiDwWgoWJxyv53IX+pIkvk1XQDmji9GT0mXMTokejMYVT35ISx3N+8i2SmS9MqT+Du+2viuqADDNRkvZKBT7qKqredYa3KF0VRm1STRXseIPY8dVMyxaeeNPilisaSk8xBq/mWXifHVrK/wR0Eg0ukIli/bnKieA8UqKwKxCoPafTrWQyja3muJVqfH/grTajJLz9swM5woIDe1JxlBemsRsBDx/uK5DUTxlPt4P7VBARkbR2orh9ArCFDBlO2BDqwyzRlDMO0EG3wLYEzLxA8NOp39CTYb8R3mC6+noJ8lXSQ58pclWVKN8atdzYwrqEHuhirqU+HEMjgnWl76IeZwBsOZrhyYTl6BtIW+E5RiVx16VtlyJxmspAetvNmB+nvyZi+AodkXVRfW8CVk="

# DOCKER_HUB_PASSWORD
    - secure: "RLzlMhfLqwSBrZqJOVOd61suXBn+HtUR3vOZfuFYF/Qmjjj5TE41+rObZmzc54hP/ZL+OH6blnibpvfDXlX+eN38ivFQfuxkJIGL68SJsEwNBRwW39Yw6Hl5RdI41MLCH7ByN15wifLp1JKBilHJ7XGMOUjI7P0yl7JjX8GBXUCtJbVLRugo80/yn+XQ1NdnlpbpYHNjMEQFWSODPa3pSK5McWvyQjDZDgS+IkdrZmIYJPMa7bmKH5I/edUPSmXQT905FgEwq9u8XR0SyBopli21EK9l6GkXIIvmDTYz5vT26Apvi2B4Aoazlklg+KNRUJuLGerpt6kbnU0gMSUChVkFfFhOk6GRSN3a/AUfD2FOudvMhet2QvlPHx+GYdEUr5XVo5HW42pHsqfD6eDtHd8VLTsHP0q4C8V85fNMv21lkkehy2ry8fx/RRy6x4O2wg2mua+79UkGKXp75gMKzWEcth34PCFCOu37l2F8R/ANnrQ52K/8vIQ88TtU2OpYX89fHjLojBxu+WKEBGZH2LRPsZBOUHeeO5C/xKDrhZU24ORnMW8wg66Qg5GIX1KI4a8yp73Mpues5hzpJ6wkMuRrQt40ymKndLCjv8KSd+5BfP6Or/KIrzDNYdZaasjk7JNi6rcZmm9d3fTAo+Ja/mjpUCIOo3SX14luzVCJIig="
    - DOCKER_BUILD=false

stages:
  - build depends
  - build src
  - run tests
  - build docker

builddepends: &builddepends
  stage: build depends
  script:
    - $DOCKER_RUN_IN_BUILDER ./ci/build_depends.sh

buildsrc: &buildsrc
  stage: build src
  script:
    - $DOCKER_RUN_IN_BUILDER ./ci/build_depends.sh
    - $DOCKER_RUN_IN_BUILDER ./ci/build_src.sh

runtests: &runtests
  stage: run tests
  script:
    - $DOCKER_RUN_IN_BUILDER ./ci/build_depends.sh
    - $DOCKER_RUN_IN_BUILDER ./ci/build_src.sh
    - $DOCKER_RUN_IN_BUILDER ./ci/test_unittests.sh
    - if [ "$TRAVIS_EVENT_TYPE" = "cron" ]; then extended="--extended --exclude feature_pruning,feature_dbcrash"; fi
    - $DOCKER_RUN_IN_BUILDER ./ci/test_integrationtests.sh --quiet --jobs=3 ${extended}

builddocker: &builddocker
  stage: build docker
  script:
    # no need to run tests again here
    - if [ "$DOCKER_BUILD" = "true" ]; then $DOCKER_RUN_IN_BUILDER ./ci/build_depends.sh && $DOCKER_RUN_IN_BUILDER ./ci/build_src.sh && BUILD_DIR=build-ci/kii-$BUILD_TARGET ./docker/build-docker.sh; fi

jobs:
  include:
    # build depends
#    - <<: *builddepends
#      name: depends-arm-linux
#      env: BUILD_TARGET=arm-linux
#    - <<: *builddepends
#      name: depends-win32
#      env: BUILD_TARGET=win32
#    - <<: *builddepends
#      name: depends-win64
#      env: BUILD_TARGET=win64
#    - <<: *builddepends
#      name: depends-linux32
#      env: BUILD_TARGET=linux32
    - <<: *builddepends
      name: depends-linux64
      env: BUILD_TARGET=linux64
#    - <<: *builddepends
#      name: depends-linux64_nowallet
#      env: BUILD_TARGET=linux64_nowallet
#    - <<: *builddepends
#      name: depends-linux64_release
#      env:
#        - BUILD_TARGET=linux64_release
#        - DOCKER_BUILD=true
#    - <<: *builddepends
#      name: depends-mac
#      env: BUILD_TARGET=mac
#    # build source
#    - <<: *buildsrc
#      name: src-arm-linux
#      env: BUILD_TARGET=arm-linux
#    - <<: *buildsrc
#      name: src-win32
#      env: BUILD_TARGET=win32
#    - <<: *buildsrc
#      name: src-win64
#      env: BUILD_TARGET=win64
#    - <<: *buildsrc
#      name: src-linux32
#      env: BUILD_TARGET=linux32
    - <<: *buildsrc
      name: src-linux64
      env: BUILD_TARGET=linux64
#    - <<: *buildsrc
#      name: src-linux64_nowallet
#      env: BUILD_TARGET=linux64_nowallet
#    - <<: *buildsrc
#      name: src-linux64_release
#      env:
#        - BUILD_TARGET=linux64_release
#        - DOCKER_BUILD=true
#    - <<: *buildsrc
#      name: src-mac
#      env: BUILD_TARGET=mac
#    # run tests (no tests for arm-linux and mac)
#    - <<: *runtests
#      name: tests-win32
#      env: BUILD_TARGET=win32
#    - <<: *runtests
#      name: tests-win64
#      env: BUILD_TARGET=win64
#    - <<: *runtests
#      name: tests-linux32
#      env: BUILD_TARGET=linux32
    - <<: *runtests
      name: tests-linux64
      env: BUILD_TARGET=linux64
#    - <<: *runtests
#      name: tests-linux64_nowallet
#      env: BUILD_TARGET=linux64_nowallet
#    - <<: *runtests
#      name: tests-linux64_release
#      env:
#        - BUILD_TARGET=linux64_release
#        - DOCKER_BUILD=true
#    # build docker
    - <<: *builddocker
      name: docker-linux64_release
      env:
        - BUILD_TARGET=linux64_release
        - DOCKER_BUILD=true

before_cache:
  # Save builder image
  - docker save kii-builder-$BUILD_TARGET-$TRAVIS_JOB_NUMBER $(docker history -q kii-builder-$BUILD_TARGET-$TRAVIS_JOB_NUMBER | grep -v \<missing\>) | gzip -2 > $HOME/cache/docker/kii-builder-$BUILD_TARGET.tar.gz

install:
    # Fix annoying Travis bug: a branch with a single commit has an empty TRAVIS_COMMIT_RANGE sometimes
    - if [ -z "$TRAVIS_COMMIT_RANGE" ]; then export TRAVIS_COMMIT_RANGE="HEAD~..HEAD"; fi
    # Our scripts try to be Travis agnostic
    - export PULL_REQUEST="$TRAVIS_PULL_REQUEST"
    - export COMMIT_RANGE="$TRAVIS_COMMIT_RANGE"
    - export JOB_NUMBER="$TRAVIS_JOB_NUMBER"
    - export HOST_SRC_DIR=$TRAVIS_BUILD_DIR
    - export HOST_CACHE_DIR=$HOME/cache
    - export TRAVIS_COMMIT_LOG=`git log --format=fuller -1`
    - source ./ci/matrix.sh
    - mkdir -p $HOST_CACHE_DIR/docker && mkdir -p $HOST_CACHE_DIR/ccache && mkdir -p $HOST_CACHE_DIR/depends && mkdir -p $HOST_CACHE_DIR/sdk-sources
    # Keep this as it makes caching related debugging easier
    - ls -lah $HOST_CACHE_DIR && ls -lah $HOST_CACHE_DIR/depends && ls -lah $HOST_CACHE_DIR/ccache && ls -lah $HOST_CACHE_DIR/docker
    # Load cached builder image
    - if [ -f $HOST_CACHE_DIR/docker/kii-builder-$BUILD_TARGET.tar.gz ]; then zcat $HOST_CACHE_DIR/docker/kii-builder-$BUILD_TARGET.tar.gz | docker load || true; fi
    - travis_retry docker pull ubuntu:bionic
    - travis_retry docker build -t $BUILDER_IMAGE_NAME --build-arg=USER_ID=$UID --build-arg=GROUP_ID=$UID --build-arg=BUILD_TARGET=$BUILD_TARGET -f ci/Dockerfile.builder ci
before_script:
    # Make sure stdout is in blocking mode. Otherwise builds will fail due to large writes to stdout
    # See https://github.com/travis-ci/travis-ci/issues/4704. If this gets fixed, this line can also be removed.
    - python3 -c 'import os,sys,fcntl; flags = fcntl.fcntl(sys.stdout, fcntl.F_GETFL); fcntl.fcntl(sys.stdout, fcntl.F_SETFL, flags&~os.O_NONBLOCK);'
    # Build docker image only for develop branch of the main repo
    - if [ "$TRAVIS_REPO_SLUG" != "kiiglobal/kii-core" -o "$TRAVIS_BRANCH" != "develop" -o "$TRAVIS_PULL_REQUEST" != "false" ]; then export DOCKER_BUILD="false"; echo DOCKER_BUILD=$DOCKER_BUILD; fi
    # TODO: Check keys and signed commits
    #- if [ "$TRAVIS_REPO_SLUG" = "kiiglobal/kii-core" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then while read LINE; do travis_retry gpg --keyserver hkp://subset.pool.sks-keyservers.net --recv-keys $LINE; done < contrib/verify-commits/trusted-keys; fi
    #- if [ "$TRAVIS_REPO_SLUG" = "kiiglobal/kii-core" -a "$TRAVIS_EVENT_TYPE" = "cron" ]; then travis_wait 30 contrib/verify-commits/verify-commits.sh; fi
after_script:
    - echo $TRAVIS_COMMIT_RANGE
    - echo $TRAVIS_COMMIT_LOG
after_success:
    - if [ "$DOCKER_BUILD" = "true" ]; then docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASSWORD && ./docker/push-docker.sh; fi


