# errata:
# - sudo/dist/group are set so as to get Blue Box VMs, necessary for [loopback]
#   IPv6 support
dist: focal
language: c++
os: linux
#sudo: required

services:
  - docker

cache:
  ccache: true
  directories:
    - $HOME/cache

addons:
  sonarcloud:
    organization: "kiiglobal"
    token:
      secure: "Lt5NPtLvE0jdWsISPZRJ995R3nvjbxZU+oITGOXrvGvgzX+8x3X0lmibpUH1lT9MOlF4atNsqFXeOnKTiXWa2zpX+hNEwdfgfMRR2kCU5V6aMtfsUz3SPm+Auxud+0SAV3THi6zNbR3tviGWVAIhg0zx25G1QakbnFQD41gzSRpqNPyeLZCAzx91bwUKyC0b8AiSk1x9/Izhnv8bqFDZXPZqHEjKv5VX/Sk5htAeojxb6Looa/RU0nc25wK5ndOvun53iTUqwyJaEDk40jR93X84MquRULUNyeKCVs47wSz1enza5gjemhZDFE1G65BNsYm5peO3LMgf2GQb/13WIErdR5yOxGp85AFKv0kn/2NabeRMe1Hgim8WwCh6cV7OkDiHicuMBcYsI4JB2owqlC9dO3HphUxHacwBiqjTLozPsv5V0SZiAixF6UpQheW8dSBtqu63Mfq47znUsQrSH9T4wSzDtFS8bWTE4WwZqYjMVVDo0bwKrM5k9hqLE0jg7vKyG2tVjpIcvItuMm+gEiD9QnCR7r2eMTE6JXnFuR/eYKjAALMkgWHdRGyQpmkXUJmIJeRJgzHp7mFtnjScnkCERlJVQ5AlE3kkSQjVmblTZ2i8mXTSa9HVyjjgye+EDQyOjSzfD59wy6aqlW6WNmEdN7Mrx729xgNRYihWVBs="

env:
  global:
    - SONAR=true
    - ARCH="x86_64-pc-linux-gnu"
#    - SONAR_TOKEN: "2145a165fed83cfe944b62f6f8bd552860cb5931"
 
before_install:
  - sudo apt-get update -qq # make the output less noisy

script:
  - cd depends
  - echo "About to build depends with $(nproc --all)"
  - ./run-with-dots.sh make HOST=$ARCH -j$(nproc --all) > /dev/null 2>&1
  - echo "-------------------------------------"
  - echo Finished makeing depends, still at directory $(pwd)
  - cd ..
  - echo "About to make autogen.sh i directory $(pwd)"
  - ./autogen.sh
  - echo "-------------------------------------"
  - echo "About to ./configure in dire $(pwd)"
  - mkdir -p build 
  - CONFIG_SITE=$(pwd)/depends/$ARCH/share/config.site ./configure --prefix=$(pwd)/build/$ARCH
  - echo "-------------------------------------"
  - echo "About to make with -j$(nproc --all)"
  - build-wrapper-linux-x86-64 --out-dir bw-output make make -j$(nproc --all) || ( echo "Build failure. Verbose build follows." && false )
  - echo "-------------------------------------"
  - echo "About to run sonar-scanner"
  - sonar-scanner -Dsonar.cfamily.build-wrapper-output=bw-output
  - echo "-------------------------------------"
  - echo "Process ended"
